- hosts: all
  connection: local
  gather_facts: false
  tasks:
  - name: pause
    pause:
      seconds: 30
    register: result
  - name: show result
    debug:
      var: result
      
- name: install the latest version of packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ VAR_packages }} "

- name: Check yum list
  shell: yum list installed | grep "{{ item }}"
  register: result
  with_items:
    - "{{ VAR_packages }}"
